language: php

os:
  - linux

dist: xenial

php:
  - 7.3.27

env:
  global:
    - XDEBUG_MODE=coverage

install:
  - composer install --no-interaction
  - composer require --dev php-coveralls/php-coveralls

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
